name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - snapshot
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Install websocket
      run: |
        curl --silent --remote-name https://raw.githubusercontent.com/ahyatt/emacs-websocket/master/websocket.el
        emacs -Q --batch -f batch-byte-compile websocket.el
    - name: Checkdoc
      run: |
        if emacs -Q --batch --eval '(checkdoc-file "edit-chrome-textarea.el")' 2>&1 | grep .; then false; else true; fi
    - name: Byte compile
      run: |
        emacs -Q --batch -L . --eval "(setq byte-compile-error-on-warn t)" -f batch-byte-compile edit-chrome-textarea.el
